-- nutritionist seed data
SET DEFINE OFF;

TRUNCATE TABLE PurchaseRequest;
TRUNCATE TABLE RawContract;
TRUNCATE TABLE Vendor;
TRUNCATE TABLE MealReviewItem;
TRUNCATE TABLE MealReview;
TRUNCATE TABLE AltReview;
TRUNCATE TABLE AltAssign;
TRUNCATE TABLE ConsumerAllergy;
TRUNCATE TABLE Consumer;
TRUNCATE TABLE MealComp;
TRUNCATE TABLE Meal;
TRUNCATE TABLE MealPlan;
TRUNCATE TABLE MenuComp;
TRUNCATE TABLE MenuTagMap;
TRUNCATE TABLE MenuTag;
TRUNCATE TABLE FinalMenu;
TRUNCATE TABLE IngredientComp;
TRUNCATE TABLE Ingredient;
TRUNCATE TABLE RawAllergy;
TRUNCATE TABLE RawNutrient;
TRUNCATE TABLE Allergy;
TRUNCATE TABLE Nutrient;
TRUNCATE TABLE RawMaterial;
TRUNCATE TABLE RawCategory;
TRUNCATE TABLE AppUser;

INSERT INTO AppUser (UserID, UserName, UserType, PasswordHash, PasswordSalt, Status, FailedLoginCount, CreatedAt, CreatedBy) VALUES ('admin', '관리자', 'ADMIN', 'RLIhW2H1hMf5KJe5ya8iAqoDObDsgUmy4c+VIyM4s7o=', 'cEzIC3GA1wg1K+B9sBdBLA==', 'ACTIVE', 0, SYSDATE, 'admin');
INSERT INTO AppUser (UserID, UserName, UserType, PasswordHash, PasswordSalt, Status, FailedLoginCount, CreatedAt, CreatedBy) VALUES ('diet01', '김영양', 'DIET', 'QRmvzWDq048qCyTsHtj8YEoC9Kfc1FbM+GlcZ+lPieA=', 'qPZBmWI263XD3zhEVmQ76A==', 'ACTIVE', 0, SYSDATE, 'admin');
INSERT INTO AppUser (UserID, UserName, UserType, PasswordHash, PasswordSalt, Status, FailedLoginCount, CreatedAt, CreatedBy) VALUES ('diet02', '이조리', 'DIET', 'PgZU+KxUOz+b5Gs9GX+T93qWGmsDcI/qDSMlF3tjmyA=', '84MP9f8tyc3/d6ZFp+blaQ==', 'ACTIVE', 0, SYSDATE, 'admin');

INSERT INTO RawCategory (RawCategoryID, CategoryCode, CategoryName, ActiveFlag) VALUES (1, 'GRAIN', '곡류', 'Y');
INSERT INTO RawCategory (RawCategoryID, CategoryCode, CategoryName, ActiveFlag) VALUES (2, 'VEGE', '채소류', 'Y');
INSERT INTO RawCategory (RawCategoryID, CategoryCode, CategoryName, ActiveFlag) VALUES (3, 'FRUIT', '과일류', 'Y');
INSERT INTO RawCategory (RawCategoryID, CategoryCode, CategoryName, ActiveFlag) VALUES (4, 'MEAT', '육류', 'Y');
INSERT INTO RawCategory (RawCategoryID, CategoryCode, CategoryName, ActiveFlag) VALUES (5, 'SEAFOOD', '수산물', 'Y');
INSERT INTO RawCategory (RawCategoryID, CategoryCode, CategoryName, ActiveFlag) VALUES (6, 'DAIRY', '유제품', 'Y');
INSERT INTO RawCategory (RawCategoryID, CategoryCode, CategoryName, ActiveFlag) VALUES (7, 'SAUCE', '조미료', 'Y');
INSERT INTO RawCategory (RawCategoryID, CategoryCode, CategoryName, ActiveFlag) VALUES (8, 'PROCESSED', '가공품', 'Y');

INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (1, '백미', 1, 'KG', 20000, '상온', 365, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (2, '현미', 1, 'KG', 20000, '상온', 365, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (3, '찹쌀', 1, 'KG', 20000, '상온', 365, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (4, '보리쌀', 1, 'KG', 20000, '상온', 365, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (5, '칼국수면', 1, 'POUCH', 10, '상온', 180, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (6, '잡곡믹스', 1, 'KG', 15000, '상온', 365, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (7, '옥수수쌀', 1, 'KG', 15000, '상온', 365, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (8, '양파', 2, 'KG', 20000, '상온', 30, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (9, '대파', 2, 'KG', 10000, '상온', 20, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (10, '마늘', 2, 'KG', 10000, '상온', 45, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (11, '당근', 2, 'KG', 15000, '냉장', 30, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (12, '감자', 2, 'KG', 20000, '상온', 30, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (13, '호박', 2, 'EA', 20, '냉장', 15, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (14, '배추', 2, 'EA', 30, '냉장', 15, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (15, '무', 2, 'EA', 30, '냉장', 20, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (16, '시금치', 2, 'KG', 8000, '냉장', 7, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (17, '청경채', 2, 'KG', 5000, '냉장', 10, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (18, '버섯믹스', 2, 'KG', 5000, '냉장', 10, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (19, '파프리카', 2, 'EA', 60, '냉장', 12, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (20, '사과', 3, 'BOX', 90, '냉장', 20, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (21, '배', 3, 'BOX', 90, '냉장', 20, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (22, '바나나', 3, 'BOX', 13, '상온', 7, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (23, '귤', 3, 'BOX', 120, '상온', 14, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (24, '수박', 3, 'EA', 20, '상온', 7, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (25, '딸기', 3, 'BOX', 24, '냉장', 5, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (26, '포도', 3, 'BOX', 24, '냉장', 10, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (27, '닭가슴살', 4, 'KG', 10000, '냉장', 10, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (28, '닭다리', 4, 'KG', 10000, '냉장', 10, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (29, '돼지 앞다리살', 4, 'KG', 10000, '냉장', 10, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (30, '돼지등심', 4, 'KG', 10000, '냉장', 10, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (31, '소불고기', 4, 'KG', 10000, '냉장', 7, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (32, '쇠고기국거리', 4, 'KG', 10000, '냉장', 7, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (33, '계란', 4, '판', 30, '냉장', 25, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (34, '명태포', 5, 'KG', 10000, '냉동', 180, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (35, '오징어', 5, 'KG', 10000, '냉동', 120, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (36, '새우살', 5, 'KG', 10000, '냉동', 120, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (37, '고등어', 5, 'EA', 40, '냉동', 90, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (38, '연어', 5, 'KG', 10000, '냉장', 7, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (39, '바지락살', 5, 'KG', 8000, '냉동', 90, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (40, '우유', 6, 'BOX', 12, '냉장', 10, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (41, '요거트', 6, 'BOX', 20, '냉장', 14, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (42, '치즈슬라이스', 6, 'BOX', 80, '냉장', 60, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (43, '버터', 6, 'KG', 20, '냉장', 90, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (44, '연유', 6, 'CAN', 24, '상온', 365, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (45, '간장', 7, 'BOTTLE', 12, '상온', 365, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (46, '고추장', 7, 'KG', 20, '상온', 365, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (47, '된장', 7, 'KG', 20, '상온', 365, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (48, '식초', 7, 'BOTTLE', 12, '상온', 365, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (49, '설탕', 7, 'KG', 20, '상온', 365, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (50, '소금', 7, 'KG', 20, '상온', 365, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (51, '참기름', 7, 'BOTTLE', 12, '상온', 365, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (52, '깨소금', 7, 'KG', 10, '상온', 365, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (53, '후추', 7, 'BOTTLE', 24, '상온', 365, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (54, '햄슬라이스', 8, 'KG', 50, '냉장', 40, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (55, '비엔나소시지', 8, 'KG', 50, '냉장', 40, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (56, '김치', 8, 'KG', 10, '냉장', 30, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (57, '떡볶이떡', 8, 'KG', 30, '냉장', 20, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (58, '라면사리', 8, 'POUCH', 40, '상온', 365, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (59, '토마토소스', 8, 'CAN', 24, '상온', 365, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (60, '카레분말', 8, 'KG', 30, '상온', 365, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (61, '옥수수콘', 8, 'CAN', 24, '상온', 365, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (62, '두부', 8, 'EA', 40, '냉장', 14, 'Y');
INSERT INTO RawMaterial (RawID, RawName, RawCategoryID, PurchaseUnit, BaseUnitQty, StorageType, ShelfLifeDays, ActiveFlag) VALUES (63, '유부', 8, 'PACK', 60, '냉동', 120, 'Y');

INSERT INTO Nutrient (NutrientID, NutrientCode, NutrientName, Unit, ActiveFlag) VALUES (1, 'CAL', '열량', 'kcal', 'Y');
INSERT INTO Nutrient (NutrientID, NutrientCode, NutrientName, Unit, ActiveFlag) VALUES (2, 'PROT', '단백질', 'g', 'Y');
INSERT INTO Nutrient (NutrientID, NutrientCode, NutrientName, Unit, ActiveFlag) VALUES (3, 'FAT', '지방', 'g', 'Y');
INSERT INTO Nutrient (NutrientID, NutrientCode, NutrientName, Unit, ActiveFlag) VALUES (4, 'CARB', '탄수화물', 'g', 'Y');
INSERT INTO Nutrient (NutrientID, NutrientCode, NutrientName, Unit, ActiveFlag) VALUES (5, 'FIB', '식이섬유', 'g', 'Y');
INSERT INTO Nutrient (NutrientID, NutrientCode, NutrientName, Unit, ActiveFlag) VALUES (6, 'VITC', '비타민C', 'mg', 'Y');
INSERT INTO Nutrient (NutrientID, NutrientCode, NutrientName, Unit, ActiveFlag) VALUES (7, 'CA', '칼슘', 'mg', 'Y');
INSERT INTO Nutrient (NutrientID, NutrientCode, NutrientName, Unit, ActiveFlag) VALUES (8, 'IRON', '철', 'mg', 'Y');

INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (1, 2, 28.23);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (1, 1, 23.1);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (1, 6, 73.91);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (2, 2, 4.15);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (2, 5, 10.28);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (2, 4, 24.03);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (3, 1, 71.89);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (3, 5, 70.43);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (3, 2, 42.53);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (4, 8, 81.13);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (4, 5, 1.64);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (4, 3, 80.78);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (5, 7, 16.39);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (5, 3, 95.76);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (5, 8, 34.32);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (6, 2, 36.54);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (6, 4, 35.05);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (6, 1, 27.19);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (7, 1, 54.09);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (7, 6, 97.34);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (7, 4, 38.47);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (8, 5, 62.23);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (8, 7, 86.31);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (8, 6, 58.16);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (9, 2, 23.56);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (9, 1, 29.65);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (9, 6, 8.9);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (10, 4, 38.63);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (10, 7, 45.89);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (10, 1, 83.58);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (11, 3, 21.74);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (11, 8, 27.43);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (11, 7, 93.73);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (12, 2, 17.94);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (12, 5, 73.18);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (12, 6, 17.18);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (13, 7, 69.13);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (13, 3, 22.74);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (13, 6, 33.1);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (14, 1, 80.7);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (14, 2, 40.72);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (14, 8, 7.55);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (15, 6, 50.42);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (15, 2, 88.58);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (15, 8, 64.64);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (16, 3, 25.42);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (16, 8, 56.58);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (16, 2, 27.01);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (17, 7, 36.84);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (17, 5, 99.74);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (17, 4, 14.69);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (18, 8, 86.25);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (18, 1, 16.13);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (18, 7, 16.84);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (19, 7, 39.09);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (19, 5, 59.99);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (19, 1, 47.34);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (20, 5, 68.35);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (20, 8, 12.34);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (20, 1, 88.59);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (21, 5, 34.68);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (21, 7, 30.06);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (21, 6, 16.66);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (22, 1, 27.08);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (22, 6, 50.56);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (22, 7, 18.69);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (23, 2, 30.55);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (23, 7, 64.26);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (23, 6, 61.29);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (24, 3, 54.4);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (24, 8, 78.08);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (24, 2, 53.51);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (25, 1, 49.37);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (25, 5, 12.07);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (25, 3, 36.94);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (26, 5, 24.85);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (26, 2, 57.17);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (26, 1, 8.8);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (27, 8, 97.82);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (27, 7, 53.74);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (27, 1, 13.45);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (28, 8, 27.24);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (28, 5, 87.37);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (28, 2, 42.89);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (29, 4, 69.3);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (29, 5, 71.58);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (29, 6, 40.5);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (30, 6, 45.7);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (30, 4, 25.54);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (30, 5, 7.34);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (31, 1, 23.78);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (31, 5, 22.8);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (31, 7, 8.03);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (32, 1, 90.64);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (32, 2, 86.1);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (32, 8, 8.01);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (33, 4, 49.06);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (33, 3, 54.38);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (33, 6, 72.61);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (34, 8, 80.94);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (34, 2, 19.85);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (34, 4, 10.6);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (35, 7, 41.7);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (35, 3, 86.52);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (35, 4, 6.36);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (36, 2, 73.09);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (36, 1, 80.26);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (36, 4, 11.82);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (37, 4, 45.41);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (37, 2, 42.77);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (37, 5, 28.58);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (38, 4, 44.87);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (38, 7, 86.27);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (38, 1, 55.48);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (39, 1, 83.77);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (39, 6, 96.93);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (39, 5, 92.71);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (40, 4, 49.08);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (40, 2, 22.16);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (40, 8, 40.7);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (41, 1, 1.21);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (41, 2, 39.65);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (41, 4, 92.73);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (42, 8, 69.96);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (42, 3, 73.32);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (42, 4, 78.55);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (43, 8, 30.37);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (43, 2, 96.9);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (43, 7, 58.34);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (44, 1, 6.66);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (44, 6, 58.83);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (44, 3, 50.78);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (45, 3, 8.93);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (45, 1, 19.4);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (45, 5, 59.91);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (46, 4, 94.22);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (46, 8, 57.4);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (46, 1, 58.31);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (47, 1, 42.5);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (47, 5, 58.78);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (47, 8, 52.76);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (48, 5, 71.9);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (48, 2, 24.63);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (48, 6, 40.18);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (49, 5, 92.97);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (49, 4, 93.64);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (49, 3, 1.92);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (50, 2, 22.1);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (50, 1, 27.25);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (50, 5, 93.39);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (51, 2, 29.21);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (51, 8, 44.38);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (51, 3, 54.78);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (52, 5, 53.37);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (52, 8, 67.12);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (52, 6, 55.91);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (53, 2, 12.43);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (53, 8, 11.6);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (53, 3, 55.77);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (54, 5, 21.85);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (54, 3, 34.95);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (54, 8, 69.06);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (55, 5, 25.86);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (55, 8, 90.91);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (55, 4, 6.03);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (56, 7, 5.36);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (56, 8, 34.02);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (56, 3, 13.95);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (57, 5, 44.74);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (57, 2, 70.86);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (57, 6, 56.53);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (58, 2, 90.49);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (58, 1, 55.01);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (58, 6, 83.62);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (59, 3, 5.14);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (59, 4, 37.1);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (59, 2, 93.38);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (60, 1, 68.52);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (60, 3, 67.03);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (60, 2, 36.01);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (61, 7, 16.3);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (61, 5, 93.06);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (61, 6, 86.6);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (62, 3, 18.76);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (62, 4, 92.52);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (62, 1, 78.46);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (63, 7, 86.54);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (63, 8, 81.26);
INSERT INTO RawNutrient (RawID, NutrientID, AmountPerBase) VALUES (63, 6, 27.41);

INSERT INTO Allergy (AllergyID, AllergyCode, AllergyName) VALUES (1, 'A01', '난류');
INSERT INTO Allergy (AllergyID, AllergyCode, AllergyName) VALUES (2, 'A02', '우유');
INSERT INTO Allergy (AllergyID, AllergyCode, AllergyName) VALUES (3, 'A03', '메밀');
INSERT INTO Allergy (AllergyID, AllergyCode, AllergyName) VALUES (4, 'A04', '땅콩');
INSERT INTO Allergy (AllergyID, AllergyCode, AllergyName) VALUES (5, 'A05', '대두');
INSERT INTO Allergy (AllergyID, AllergyCode, AllergyName) VALUES (6, 'A06', '밀');
INSERT INTO Allergy (AllergyID, AllergyCode, AllergyName) VALUES (7, 'A07', '고등어');
INSERT INTO Allergy (AllergyID, AllergyCode, AllergyName) VALUES (8, 'A08', '게');
INSERT INTO Allergy (AllergyID, AllergyCode, AllergyName) VALUES (9, 'A09', '새우');
INSERT INTO Allergy (AllergyID, AllergyCode, AllergyName) VALUES (10, 'A10', '돼지고기');
INSERT INTO Allergy (AllergyID, AllergyCode, AllergyName) VALUES (11, 'A11', '복숭아');
INSERT INTO Allergy (AllergyID, AllergyCode, AllergyName) VALUES (12, 'A12', '토마토');
INSERT INTO Allergy (AllergyID, AllergyCode, AllergyName) VALUES (13, 'A13', '호두');
INSERT INTO Allergy (AllergyID, AllergyCode, AllergyName) VALUES (14, 'A14', '닭고기');
INSERT INTO Allergy (AllergyID, AllergyCode, AllergyName) VALUES (15, 'A15', '쇠고기');

INSERT INTO RawAllergy (RawID, AllergyID, EvidenceNote) VALUES (5, 6, NULL);
INSERT INTO RawAllergy (RawID, AllergyID, EvidenceNote) VALUES (27, 14, NULL);
INSERT INTO RawAllergy (RawID, AllergyID, EvidenceNote) VALUES (28, 14, NULL);
INSERT INTO RawAllergy (RawID, AllergyID, EvidenceNote) VALUES (29, 10, NULL);
INSERT INTO RawAllergy (RawID, AllergyID, EvidenceNote) VALUES (30, 10, NULL);
INSERT INTO RawAllergy (RawID, AllergyID, EvidenceNote) VALUES (31, 15, NULL);
INSERT INTO RawAllergy (RawID, AllergyID, EvidenceNote) VALUES (32, 15, NULL);
INSERT INTO RawAllergy (RawID, AllergyID, EvidenceNote) VALUES (33, 1, NULL);
INSERT INTO RawAllergy (RawID, AllergyID, EvidenceNote) VALUES (36, 9, NULL);
INSERT INTO RawAllergy (RawID, AllergyID, EvidenceNote) VALUES (37, 7, NULL);
INSERT INTO RawAllergy (RawID, AllergyID, EvidenceNote) VALUES (40, 2, NULL);
INSERT INTO RawAllergy (RawID, AllergyID, EvidenceNote) VALUES (41, 2, NULL);
INSERT INTO RawAllergy (RawID, AllergyID, EvidenceNote) VALUES (42, 2, NULL);
INSERT INTO RawAllergy (RawID, AllergyID, EvidenceNote) VALUES (43, 2, NULL);
INSERT INTO RawAllergy (RawID, AllergyID, EvidenceNote) VALUES (50, 15, NULL);
INSERT INTO RawAllergy (RawID, AllergyID, EvidenceNote) VALUES (52, 15, NULL);
INSERT INTO RawAllergy (RawID, AllergyID, EvidenceNote) VALUES (55, 15, NULL);
INSERT INTO RawAllergy (RawID, AllergyID, EvidenceNote) VALUES (58, 6, NULL);
INSERT INTO RawAllergy (RawID, AllergyID, EvidenceNote) VALUES (59, 15, NULL);
INSERT INTO RawAllergy (RawID, AllergyID, EvidenceNote) VALUES (59, 12, NULL);
INSERT INTO RawAllergy (RawID, AllergyID, EvidenceNote) VALUES (62, 5, NULL);

INSERT INTO Ingredient (IngredientID, IngredientName, Type, BatchYieldGram, DefaultPortionGram, ActiveFlag) VALUES (1, '고추장볶음양념', 'SAUCE', 5000, 25, 'Y');
INSERT INTO Ingredient (IngredientID, IngredientName, Type, BatchYieldGram, DefaultPortionGram, ActiveFlag) VALUES (2, '간장마리네이드', 'MARINADE', 6000, 30, 'Y');
INSERT INTO Ingredient (IngredientID, IngredientName, Type, BatchYieldGram, DefaultPortionGram, ActiveFlag) VALUES (3, '카레소스베이스', 'BASE', 8000, 120, 'Y');
INSERT INTO Ingredient (IngredientID, IngredientName, Type, BatchYieldGram, DefaultPortionGram, ActiveFlag) VALUES (4, '조림양념베이스', 'SAUCE', 4500, 35, 'Y');
INSERT INTO Ingredient (IngredientID, IngredientName, Type, BatchYieldGram, DefaultPortionGram, ActiveFlag) VALUES (5, '샐러드드레싱', 'DRESSING', 3000, 20, 'Y');
INSERT INTO Ingredient (IngredientID, IngredientName, Type, BatchYieldGram, DefaultPortionGram, ActiveFlag) VALUES (6, '튀김반죽', 'BATTER', 7000, 40, 'Y');

INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (1, 46, 1500, 5);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (1, 45, 800, 3);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (1, 10, 400, 2);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (1, 49, 350, 1);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (1, 51, 200, 0);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (2, 45, 900, 2);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (2, 10, 350, 2);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (2, 21, 500, 1.5);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (2, 52, 200, 0);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (2, 53, 50, 0);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (3, 8, 1200, 5);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (3, 11, 700, 3);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (3, 12, 900, 3);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (3, 60, 400, 0);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (3, 43, 200, 0);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (4, 45, 700, 2.5);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (4, 49, 400, 1.5);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (4, 10, 250, 1);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (4, 9, 250, 1);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (4, 48, 150, 0);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (5, 41, 1200, 2);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (5, 20, 500, 4);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (5, 48, 200, 1);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (5, 49, 150, 0);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (5, 50, 50, 0);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (6, 3, 1200, 4);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (6, 7, 900, 4);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (6, 33, 500, 2);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (6, 50, 80, 1);
INSERT INTO IngredientComp (IngredientID, RawID, QuantityPerBatch, LossRatePct) VALUES (6, 51, 50, 0);

INSERT INTO FinalMenu (FinalMenuID, MenuCode, MenuName, MenuType, ServingSizeGram, ActiveFlag) VALUES (1, 'FM001', '참치김치볶음밥', 'MAIN', 250, 'Y');
INSERT INTO FinalMenu (FinalMenuID, MenuCode, MenuName, MenuType, ServingSizeGram, ActiveFlag) VALUES (2, 'FM002', '닭갈비덮밥', 'MAIN', 280, 'Y');
INSERT INTO FinalMenu (FinalMenuID, MenuCode, MenuName, MenuType, ServingSizeGram, ActiveFlag) VALUES (3, 'FM003', '미역국', 'SOUP', 200, 'Y');
INSERT INTO FinalMenu (FinalMenuID, MenuCode, MenuName, MenuType, ServingSizeGram, ActiveFlag) VALUES (4, 'FM004', '된장찌개', 'SOUP', 220, 'Y');
INSERT INTO FinalMenu (FinalMenuID, MenuCode, MenuName, MenuType, ServingSizeGram, ActiveFlag) VALUES (5, 'FM005', '고등어조림', 'SIDE', 180, 'Y');
INSERT INTO FinalMenu (FinalMenuID, MenuCode, MenuName, MenuType, ServingSizeGram, ActiveFlag) VALUES (6, 'FM006', '쇠고기불고기', 'SIDE', 200, 'Y');
INSERT INTO FinalMenu (FinalMenuID, MenuCode, MenuName, MenuType, ServingSizeGram, ActiveFlag) VALUES (7, 'FM007', '야채튀김', 'SIDE', 150, 'Y');
INSERT INTO FinalMenu (FinalMenuID, MenuCode, MenuName, MenuType, ServingSizeGram, ActiveFlag) VALUES (8, 'FM008', '과일샐러드', 'SIDE', 120, 'Y');
INSERT INTO FinalMenu (FinalMenuID, MenuCode, MenuName, MenuType, ServingSizeGram, ActiveFlag) VALUES (9, 'FM009', '비빔국수', 'MAIN', 300, 'Y');
INSERT INTO FinalMenu (FinalMenuID, MenuCode, MenuName, MenuType, ServingSizeGram, ActiveFlag) VALUES (10, 'FM010', '김치볶음밥', 'MAIN', 260, 'Y');
INSERT INTO FinalMenu (FinalMenuID, MenuCode, MenuName, MenuType, ServingSizeGram, ActiveFlag) VALUES (11, 'FM011', '카레라이스', 'MAIN', 300, 'Y');
INSERT INTO FinalMenu (FinalMenuID, MenuCode, MenuName, MenuType, ServingSizeGram, ActiveFlag) VALUES (12, 'FM012', '어묵국', 'SOUP', 210, 'Y');
INSERT INTO FinalMenu (FinalMenuID, MenuCode, MenuName, MenuType, ServingSizeGram, ActiveFlag) VALUES (13, 'FM013', '닭개장', 'SOUP', 240, 'Y');
INSERT INTO FinalMenu (FinalMenuID, MenuCode, MenuName, MenuType, ServingSizeGram, ActiveFlag) VALUES (14, 'FM014', '연어스테이크', 'SIDE', 200, 'Y');
INSERT INTO FinalMenu (FinalMenuID, MenuCode, MenuName, MenuType, ServingSizeGram, ActiveFlag) VALUES (15, 'FM015', '새우튀김', 'SIDE', 180, 'Y');
INSERT INTO FinalMenu (FinalMenuID, MenuCode, MenuName, MenuType, ServingSizeGram, ActiveFlag) VALUES (16, 'FM016', '돼지고기장조림', 'SIDE', 150, 'Y');
INSERT INTO FinalMenu (FinalMenuID, MenuCode, MenuName, MenuType, ServingSizeGram, ActiveFlag) VALUES (17, 'FM017', '두부조림', 'SIDE', 160, 'Y');
INSERT INTO FinalMenu (FinalMenuID, MenuCode, MenuName, MenuType, ServingSizeGram, ActiveFlag) VALUES (18, 'FM018', '계란찜', 'SIDE', 150, 'Y');
INSERT INTO FinalMenu (FinalMenuID, MenuCode, MenuName, MenuType, ServingSizeGram, ActiveFlag) VALUES (19, 'FM019', '과일플래터', 'SIDE', 130, 'Y');
INSERT INTO FinalMenu (FinalMenuID, MenuCode, MenuName, MenuType, ServingSizeGram, ActiveFlag) VALUES (20, 'FM020', '우유', 'DRINK', 200, 'Y');

INSERT INTO MenuTag (MenuTagID, TagName, TagType, Description, ActiveFlag) VALUES (1, '저염', 'NUTRITION', '나트륨을 줄인 메뉴', 'Y');
INSERT INTO MenuTag (MenuTagID, TagName, TagType, Description, ActiveFlag) VALUES (2, '고단백', 'NUTRITION', '단백질 함량을 높인 메뉴', 'Y');
INSERT INTO MenuTag (MenuTagID, TagName, TagType, Description, ActiveFlag) VALUES (3, '채식가능', 'DIET', '동물성 재료를 최소화한 메뉴', 'Y');
INSERT INTO MenuTag (MenuTagID, TagName, TagType, Description, ActiveFlag) VALUES (4, '어린이인기', 'PREF', '학생 선호도가 높은 메뉴', 'Y');
INSERT INTO MenuTag (MenuTagID, TagName, TagType, Description, ActiveFlag) VALUES (5, '계절과일', 'SEASONAL', '제철 과일을 활용한 메뉴', 'Y');
INSERT INTO MenuTag (MenuTagID, TagName, TagType, Description, ActiveFlag) VALUES (6, '대체식', 'SPECIAL', '알레르기 대체 메뉴 제공 가능', 'Y');

INSERT INTO MenuTagMap (FinalMenuID, MenuTagID, TagPriority) VALUES (1, 4, 1);
INSERT INTO MenuTagMap (FinalMenuID, MenuTagID, TagPriority) VALUES (1, 2, 2);
INSERT INTO MenuTagMap (FinalMenuID, MenuTagID, TagPriority) VALUES (2, 2, 1);
INSERT INTO MenuTagMap (FinalMenuID, MenuTagID, TagPriority) VALUES (3, 1, 1);
INSERT INTO MenuTagMap (FinalMenuID, MenuTagID, TagPriority) VALUES (4, 1, 1);
INSERT INTO MenuTagMap (FinalMenuID, MenuTagID, TagPriority) VALUES (6, 2, 1);
INSERT INTO MenuTagMap (FinalMenuID, MenuTagID, TagPriority) VALUES (7, 4, 1);
INSERT INTO MenuTagMap (FinalMenuID, MenuTagID, TagPriority) VALUES (8, 3, 1);
INSERT INTO MenuTagMap (FinalMenuID, MenuTagID, TagPriority) VALUES (8, 5, 2);
INSERT INTO MenuTagMap (FinalMenuID, MenuTagID, TagPriority) VALUES (10, 4, 1);
INSERT INTO MenuTagMap (FinalMenuID, MenuTagID, TagPriority) VALUES (11, 2, 1);
INSERT INTO MenuTagMap (FinalMenuID, MenuTagID, TagPriority) VALUES (13, 1, 2);
INSERT INTO MenuTagMap (FinalMenuID, MenuTagID, TagPriority) VALUES (14, 2, 2);
INSERT INTO MenuTagMap (FinalMenuID, MenuTagID, TagPriority) VALUES (17, 6, 1);
INSERT INTO MenuTagMap (FinalMenuID, MenuTagID, TagPriority) VALUES (19, 5, 1);
INSERT INTO MenuTagMap (FinalMenuID, MenuTagID, TagPriority) VALUES (20, 6, 1);

INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (1, 1, 'R', 1, NULL, 210);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (2, 1, 'R', 56, NULL, 50);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (3, 1, 'I', NULL, 1, 25);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (4, 1, 'R', 52, NULL, 3);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (5, 2, 'R', 1, NULL, 210);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (6, 2, 'R', 27, NULL, 110);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (7, 2, 'I', NULL, 2, 35);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (8, 2, 'R', 11, NULL, 25);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (9, 3, 'R', 32, NULL, 45);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (10, 3, 'R', 15, NULL, 30);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (11, 3, 'R', 9, NULL, 5);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (12, 3, 'R', 50, NULL, 2);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (13, 4, 'R', 47, NULL, 30);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (14, 4, 'R', 62, NULL, 40);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (15, 4, 'R', 10, NULL, 5);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (16, 4, 'R', 16, NULL, 20);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (17, 5, 'R', 37, NULL, 120);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (18, 5, 'R', 15, NULL, 40);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (19, 5, 'I', NULL, 4, 30);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (20, 6, 'R', 31, NULL, 120);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (21, 6, 'I', NULL, 2, 30);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (22, 6, 'R', 11, NULL, 20);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (23, 6, 'R', 19, NULL, 15);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (24, 7, 'R', 11, NULL, 30);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (25, 7, 'R', 19, NULL, 20);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (26, 7, 'R', 12, NULL, 35);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (27, 7, 'I', NULL, 6, 40);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (28, 8, 'R', 20, NULL, 40);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (29, 8, 'R', 25, NULL, 30);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (30, 8, 'R', 23, NULL, 30);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (31, 8, 'I', NULL, 5, 20);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (32, 9, 'R', 5, NULL, 200);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (33, 9, 'I', NULL, 1, 40);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (34, 9, 'R', 8, NULL, 25);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (35, 9, 'R', 17, NULL, 20);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (36, 10, 'R', 1, NULL, 200);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (37, 10, 'R', 56, NULL, 55);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (38, 10, 'I', NULL, 1, 30);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (39, 10, 'R', 54, NULL, 25);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (40, 11, 'R', 1, NULL, 230);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (41, 11, 'I', NULL, 3, 120);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (42, 11, 'R', 12, NULL, 40);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (43, 11, 'R', 11, NULL, 25);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (44, 12, 'R', 63, NULL, 25);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (45, 12, 'R', 12, NULL, 25);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (46, 12, 'R', 9, NULL, 10);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (47, 12, 'R', 50, NULL, 2);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (48, 13, 'R', 28, NULL, 120);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (49, 13, 'R', 13, NULL, 30);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (50, 13, 'R', 9, NULL, 20);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (51, 13, 'I', NULL, 2, 25);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (52, 14, 'R', 38, NULL, 140);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (53, 14, 'R', 19, NULL, 30);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (54, 14, 'I', NULL, 2, 20);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (55, 14, 'R', 48, NULL, 5);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (56, 15, 'R', 36, NULL, 90);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (57, 15, 'I', NULL, 6, 35);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (58, 15, 'R', 52, NULL, 3);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (59, 15, 'R', 51, NULL, 2);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (60, 16, 'R', 30, NULL, 110);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (61, 16, 'R', 15, NULL, 30);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (62, 16, 'I', NULL, 4, 30);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (63, 16, 'R', 9, NULL, 15);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (64, 17, 'R', 62, NULL, 100);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (65, 17, 'I', NULL, 4, 25);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (66, 17, 'R', 16, NULL, 15);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (67, 17, 'R', 9, NULL, 10);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (68, 18, 'R', 33, NULL, 110);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (69, 18, 'R', 40, NULL, 30);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (70, 18, 'R', 50, NULL, 2);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (71, 18, 'R', 9, NULL, 5);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (72, 19, 'R', 20, NULL, 40);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (73, 19, 'R', 21, NULL, 50);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (74, 19, 'R', 24, NULL, 60);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (75, 19, 'R', 25, NULL, 30);
INSERT INTO MenuComp (MenuCompID, FinalMenuID, ComponentType, ComponentRawID, ComponentIngredientID, QuantityPerServing) VALUES (76, 20, 'R', 40, NULL, 200);

INSERT INTO MealPlan (MealPlanID, PlanName, PeriodStart, PeriodEnd, Status, CreatedBy) VALUES (1, '2024-03 식단', DATE '2024-03-01', DATE '2024-03-28', 'APPROVED', 'diet01');
INSERT INTO MealPlan (MealPlanID, PlanName, PeriodStart, PeriodEnd, Status, CreatedBy) VALUES (2, '2024-04 식단', DATE '2024-04-01', DATE '2024-04-28', 'APPROVED', 'diet01');
INSERT INTO MealPlan (MealPlanID, PlanName, PeriodStart, PeriodEnd, Status, CreatedBy) VALUES (3, '2024-05 식단', DATE '2024-05-01', DATE '2024-05-28', 'APPROVED', 'diet01');
INSERT INTO MealPlan (MealPlanID, PlanName, PeriodStart, PeriodEnd, Status, CreatedBy) VALUES (4, '2024-06 식단', DATE '2024-06-01', DATE '2024-06-28', 'DRAFT', 'diet01');
INSERT INTO MealPlan (MealPlanID, PlanName, PeriodStart, PeriodEnd, Status, CreatedBy) VALUES (5, '2024-07 식단', DATE '2024-07-01', DATE '2024-07-28', 'DRAFT', 'diet01');
INSERT INTO MealPlan (MealPlanID, PlanName, PeriodStart, PeriodEnd, Status, CreatedBy) VALUES (6, '2024-08 식단', DATE '2024-08-01', DATE '2024-08-28', 'DRAFT', 'diet01');

INSERT INTO Meal (MealID, MealPlanID, MealDate, MealType, TargetGradeFrom, TargetGradeTo, TargetGroup) VALUES (1, 1, DATE '2024-03-01', 'BREAKFAST', 1, 6, '학생');
INSERT INTO Meal (MealID, MealPlanID, MealDate, MealType, TargetGradeFrom, TargetGradeTo, TargetGroup) VALUES (2, 1, DATE '2024-03-02', 'LUNCH', 1, 6, '학생');
INSERT INTO Meal (MealID, MealPlanID, MealDate, MealType, TargetGradeFrom, TargetGradeTo, TargetGroup) VALUES (3, 1, DATE '2024-03-03', 'DINNER', 1, 6, '학생');
INSERT INTO Meal (MealID, MealPlanID, MealDate, MealType, TargetGradeFrom, TargetGradeTo, TargetGroup) VALUES (4, 2, DATE '2024-04-01', 'BREAKFAST', 1, 6, '학생');
INSERT INTO Meal (MealID, MealPlanID, MealDate, MealType, TargetGradeFrom, TargetGradeTo, TargetGroup) VALUES (5, 2, DATE '2024-04-02', 'LUNCH', 1, 6, '학생');
INSERT INTO Meal (MealID, MealPlanID, MealDate, MealType, TargetGradeFrom, TargetGradeTo, TargetGroup) VALUES (6, 2, DATE '2024-04-03', 'DINNER', 1, 6, '학생');
INSERT INTO Meal (MealID, MealPlanID, MealDate, MealType, TargetGradeFrom, TargetGradeTo, TargetGroup) VALUES (7, 3, DATE '2024-05-01', 'BREAKFAST', 1, 6, '학생');
INSERT INTO Meal (MealID, MealPlanID, MealDate, MealType, TargetGradeFrom, TargetGradeTo, TargetGroup) VALUES (8, 3, DATE '2024-05-02', 'LUNCH', 1, 6, '학생');
INSERT INTO Meal (MealID, MealPlanID, MealDate, MealType, TargetGradeFrom, TargetGradeTo, TargetGroup) VALUES (9, 3, DATE '2024-05-03', 'DINNER', 1, 6, '학생');
INSERT INTO Meal (MealID, MealPlanID, MealDate, MealType, TargetGradeFrom, TargetGradeTo, TargetGroup) VALUES (10, 4, DATE '2024-06-01', 'BREAKFAST', 1, 6, '학생');
INSERT INTO Meal (MealID, MealPlanID, MealDate, MealType, TargetGradeFrom, TargetGradeTo, TargetGroup) VALUES (11, 4, DATE '2024-06-02', 'LUNCH', 1, 6, '학생');
INSERT INTO Meal (MealID, MealPlanID, MealDate, MealType, TargetGradeFrom, TargetGradeTo, TargetGroup) VALUES (12, 4, DATE '2024-06-03', 'DINNER', 1, 6, '학생');
INSERT INTO Meal (MealID, MealPlanID, MealDate, MealType, TargetGradeFrom, TargetGradeTo, TargetGroup) VALUES (13, 5, DATE '2024-07-01', 'BREAKFAST', 1, 6, '학생');
INSERT INTO Meal (MealID, MealPlanID, MealDate, MealType, TargetGradeFrom, TargetGradeTo, TargetGroup) VALUES (14, 5, DATE '2024-07-02', 'LUNCH', 1, 6, '학생');
INSERT INTO Meal (MealID, MealPlanID, MealDate, MealType, TargetGradeFrom, TargetGradeTo, TargetGroup) VALUES (15, 5, DATE '2024-07-03', 'DINNER', 1, 6, '학생');
INSERT INTO Meal (MealID, MealPlanID, MealDate, MealType, TargetGradeFrom, TargetGradeTo, TargetGroup) VALUES (16, 6, DATE '2024-08-01', 'BREAKFAST', 1, 6, '학생');
INSERT INTO Meal (MealID, MealPlanID, MealDate, MealType, TargetGradeFrom, TargetGradeTo, TargetGroup) VALUES (17, 6, DATE '2024-08-02', 'LUNCH', 1, 6, '학생');
INSERT INTO Meal (MealID, MealPlanID, MealDate, MealType, TargetGradeFrom, TargetGradeTo, TargetGroup) VALUES (18, 6, DATE '2024-08-03', 'DINNER', 1, 6, '학생');

INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (1, 4, 189, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (1, 13, 140, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (1, 2, 108, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (2, 7, 119, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (2, 15, 185, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (2, 12, 181, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (3, 8, 164, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (3, 20, 104, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (3, 1, 131, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (4, 11, 178, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (4, 9, 115, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (4, 3, 124, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (5, 17, 122, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (5, 13, 200, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (5, 18, 83, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (6, 4, 154, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (6, 9, 113, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (6, 6, 84, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (7, 4, 173, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (7, 14, 180, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (7, 12, 120, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (8, 14, 129, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (8, 17, 195, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (8, 4, 153, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (9, 7, 170, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (9, 9, 135, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (9, 2, 80, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (10, 17, 126, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (10, 18, 135, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (10, 7, 88, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (11, 11, 172, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (11, 20, 195, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (11, 4, 118, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (12, 17, 121, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (12, 10, 131, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (12, 14, 169, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (13, 10, 104, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (13, 18, 133, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (13, 5, 165, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (14, 13, 131, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (14, 6, 150, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (14, 10, 186, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (15, 1, 106, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (15, 10, 135, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (15, 19, 180, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (16, 19, 136, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (16, 11, 136, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (16, 15, 166, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (17, 7, 181, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (17, 17, 195, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (17, 16, 181, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (18, 6, 145, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (18, 3, 164, 'N');
INSERT INTO MealComp (MealID, FinalMenuID, PortionCount, IsMainDish) VALUES (18, 10, 161, 'N');

INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (1, 'S', 1, '1-01', '1학년1반1번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (2, 'S', 1, '1-02', '1학년1반2번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (3, 'S', 1, '1-03', '1학년1반3번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (4, 'S', 1, '1-04', '1학년1반4번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (5, 'S', 1, '2-01', '1학년2반1번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (6, 'S', 1, '2-02', '1학년2반2번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (7, 'S', 1, '2-03', '1학년2반3번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (8, 'S', 1, '2-04', '1학년2반4번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (9, 'S', 2, '1-01', '2학년1반1번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (10, 'S', 2, '1-02', '2학년1반2번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (11, 'S', 2, '1-03', '2학년1반3번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (12, 'S', 2, '1-04', '2학년1반4번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (13, 'S', 2, '2-01', '2학년2반1번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (14, 'S', 2, '2-02', '2학년2반2번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (15, 'S', 2, '2-03', '2학년2반3번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (16, 'S', 2, '2-04', '2학년2반4번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (17, 'S', 3, '1-01', '3학년1반1번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (18, 'S', 3, '1-02', '3학년1반2번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (19, 'S', 3, '1-03', '3학년1반3번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (20, 'S', 3, '1-04', '3학년1반4번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (21, 'S', 3, '2-01', '3학년2반1번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (22, 'S', 3, '2-02', '3학년2반2번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (23, 'S', 3, '2-03', '3학년2반3번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (24, 'S', 3, '2-04', '3학년2반4번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (25, 'S', 4, '1-01', '4학년1반1번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (26, 'S', 4, '1-02', '4학년1반2번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (27, 'S', 4, '1-03', '4학년1반3번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (28, 'S', 4, '1-04', '4학년1반4번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (29, 'S', 4, '2-01', '4학년2반1번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (30, 'S', 4, '2-02', '4학년2반2번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (31, 'S', 4, '2-03', '4학년2반3번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (32, 'S', 4, '2-04', '4학년2반4번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (33, 'S', 5, '1-01', '5학년1반1번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (34, 'S', 5, '1-02', '5학년1반2번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (35, 'S', 5, '1-03', '5학년1반3번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (36, 'S', 5, '1-04', '5학년1반4번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (37, 'S', 5, '2-01', '5학년2반1번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (38, 'S', 5, '2-02', '5학년2반2번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (39, 'S', 5, '2-03', '5학년2반3번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (40, 'S', 5, '2-04', '5학년2반4번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (41, 'S', 6, '1-01', '6학년1반1번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (42, 'S', 6, '1-02', '6학년1반2번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (43, 'S', 6, '1-03', '6학년1반3번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (44, 'S', 6, '1-04', '6학년1반4번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (45, 'S', 6, '2-01', '6학년2반1번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (46, 'S', 6, '2-02', '6학년2반2번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (47, 'S', 6, '2-03', '6학년2반3번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (48, 'S', 6, '2-04', '6학년2반4번', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (49, 'T', NULL, NULL, '교직원1', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (50, 'T', NULL, NULL, '교직원2', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (51, 'T', NULL, NULL, '교직원3', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (52, 'T', NULL, NULL, '교직원4', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (53, 'T', NULL, NULL, '교직원5', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (54, 'T', NULL, NULL, '교직원6', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (55, 'T', NULL, NULL, '교직원7', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (56, 'T', NULL, NULL, '교직원8', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (57, 'T', NULL, NULL, '교직원9', 'ACTIVE');
INSERT INTO Consumer (ConsumerID, ConsumerType, Grade, Class, Name, Status) VALUES (58, 'T', NULL, NULL, '교직원10', 'ACTIVE');

INSERT INTO ConsumerAllergy (ConsumerID, AllergyID) VALUES (2, 11);
INSERT INTO ConsumerAllergy (ConsumerID, AllergyID) VALUES (5, 4);
INSERT INTO ConsumerAllergy (ConsumerID, AllergyID) VALUES (15, 15);
INSERT INTO ConsumerAllergy (ConsumerID, AllergyID) VALUES (18, 4);
INSERT INTO ConsumerAllergy (ConsumerID, AllergyID) VALUES (18, 3);
INSERT INTO ConsumerAllergy (ConsumerID, AllergyID) VALUES (24, 13);
INSERT INTO ConsumerAllergy (ConsumerID, AllergyID) VALUES (36, 8);
INSERT INTO ConsumerAllergy (ConsumerID, AllergyID) VALUES (36, 5);
INSERT INTO ConsumerAllergy (ConsumerID, AllergyID) VALUES (39, 11);
INSERT INTO ConsumerAllergy (ConsumerID, AllergyID) VALUES (39, 4);
INSERT INTO ConsumerAllergy (ConsumerID, AllergyID) VALUES (40, 12);
INSERT INTO ConsumerAllergy (ConsumerID, AllergyID) VALUES (41, 6);
INSERT INTO ConsumerAllergy (ConsumerID, AllergyID) VALUES (41, 15);
INSERT INTO ConsumerAllergy (ConsumerID, AllergyID) VALUES (43, 4);
INSERT INTO ConsumerAllergy (ConsumerID, AllergyID) VALUES (45, 2);
INSERT INTO ConsumerAllergy (ConsumerID, AllergyID) VALUES (49, 7);
INSERT INTO ConsumerAllergy (ConsumerID, AllergyID) VALUES (49, 13);
INSERT INTO ConsumerAllergy (ConsumerID, AllergyID) VALUES (55, 5);
INSERT INTO ConsumerAllergy (ConsumerID, AllergyID) VALUES (55, 13);

INSERT INTO AltAssign (AltAssignID, MealID, TargetFinalMenuID, AllergyID, FinalMenuID, TargetConsumerCount) VALUES (1, 13, 5, 7, 19, 3);
INSERT INTO AltAssign (AltAssignID, MealID, TargetFinalMenuID, AllergyID, FinalMenuID, TargetConsumerCount) VALUES (2, 3, 20, 2, 8, 5);
INSERT INTO AltAssign (AltAssignID, MealID, TargetFinalMenuID, AllergyID, FinalMenuID, TargetConsumerCount) VALUES (3, 12, 17, 5, 10, 4);
INSERT INTO AltAssign (AltAssignID, MealID, TargetFinalMenuID, AllergyID, FinalMenuID, TargetConsumerCount) VALUES (4, 14, 6, 15, 8, 2);

INSERT INTO AltReview (AltAssignID, ConsumerID, Rating, CommentText, CreatedAt) VALUES (1, 49, 5, '과일 플래터 대체식이 만족스러웠어요', DATE '2024-07-13');
INSERT INTO AltReview (AltAssignID, ConsumerID, Rating, CommentText, CreatedAt) VALUES (2, 45, 4, '과일샐러드로 대체되어 부담이 없었어요', DATE '2024-07-04');
INSERT INTO AltReview (AltAssignID, ConsumerID, Rating, CommentText, CreatedAt) VALUES (3, 36, 4, '김치볶음밥 대체식도 든든했습니다', DATE '2024-07-12');
INSERT INTO AltReview (AltAssignID, ConsumerID, Rating, CommentText, CreatedAt) VALUES (3, 55, 5, '대체식을 더 선호해요', DATE '2024-07-12');
INSERT INTO AltReview (AltAssignID, ConsumerID, Rating, CommentText, CreatedAt) VALUES (4, 15, 3, '과일로 대체되어 무난했어요', DATE '2024-07-18');

INSERT INTO MealReview (MealID, ConsumerID, OverallRating, CommentText, CreatedAt) VALUES (2, 5, 4, '새우튀김이 바삭했어요', DATE '2024-07-02');
INSERT INTO MealReview (MealID, ConsumerID, OverallRating, CommentText, CreatedAt) VALUES (5, 12, 3, '닭개장이 조금 짰어요', DATE '2024-07-05');
INSERT INTO MealReview (MealID, ConsumerID, OverallRating, CommentText, CreatedAt) VALUES (11, 52, 5, '카레라이스가 특히 맛있었습니다', DATE '2024-07-11');
INSERT INTO MealReview (MealID, ConsumerID, OverallRating, CommentText, CreatedAt) VALUES (16, 49, 4, '과일플래터가 신선했어요', DATE '2024-07-16');

INSERT INTO MealReviewItem (MealID, ConsumerID, FinalMenuID, ItemRating) VALUES (2, 5, 7, 4);
INSERT INTO MealReviewItem (MealID, ConsumerID, FinalMenuID, ItemRating) VALUES (2, 5, 15, 5);
INSERT INTO MealReviewItem (MealID, ConsumerID, FinalMenuID, ItemRating) VALUES (2, 5, 12, 4);
INSERT INTO MealReviewItem (MealID, ConsumerID, FinalMenuID, ItemRating) VALUES (5, 12, 17, 4);
INSERT INTO MealReviewItem (MealID, ConsumerID, FinalMenuID, ItemRating) VALUES (5, 12, 13, 2);
INSERT INTO MealReviewItem (MealID, ConsumerID, FinalMenuID, ItemRating) VALUES (5, 12, 18, 3);
INSERT INTO MealReviewItem (MealID, ConsumerID, FinalMenuID, ItemRating) VALUES (11, 52, 11, 5);
INSERT INTO MealReviewItem (MealID, ConsumerID, FinalMenuID, ItemRating) VALUES (11, 52, 20, 4);
INSERT INTO MealReviewItem (MealID, ConsumerID, FinalMenuID, ItemRating) VALUES (11, 52, 4, 5);
INSERT INTO MealReviewItem (MealID, ConsumerID, FinalMenuID, ItemRating) VALUES (16, 49, 19, 5);
INSERT INTO MealReviewItem (MealID, ConsumerID, FinalMenuID, ItemRating) VALUES (16, 49, 11, 4);
INSERT INTO MealReviewItem (MealID, ConsumerID, FinalMenuID, ItemRating) VALUES (16, 49, 15, 3);

INSERT INTO Vendor (VendorID, VendorName, BusinessNumber, ContactName, ContactPhone, Address, DefaultLeadTimeDays, Status) VALUES (1, '한빛유통', '123-45-67890', '김유통', '010-1111-2222', '서울시 중구 식자재로 11', 3, 'ACTIVE');
INSERT INTO Vendor (VendorID, VendorName, BusinessNumber, ContactName, ContactPhone, Address, DefaultLeadTimeDays, Status) VALUES (2, '그린푸드협동조합', '234-56-78901', '박식재', '010-3333-4444', '경기도 성남시 친환경로 52', 4, 'ACTIVE');
INSERT INTO Vendor (VendorID, VendorName, BusinessNumber, ContactName, ContactPhone, Address, DefaultLeadTimeDays, Status) VALUES (3, '씨푸드마켓', '345-67-89012', '최수산', '010-5555-6666', '부산시 수영구 해안로 88', 5, 'ACTIVE');

INSERT INTO RawContract (RawContractID, VendorID, RawID, ContractPrice, Currency, EffectiveStart, EffectiveEnd, MinOrderQty, Notes) VALUES (1, 1, 1, 2850.00, 'KRW', DATE '2024-01-01', DATE '2024-12-31', 20, '월단위 정산');
INSERT INTO RawContract (RawContractID, VendorID, RawID, ContractPrice, Currency, EffectiveStart, EffectiveEnd, MinOrderQty, Notes) VALUES (2, 2, 8, 920.00, 'KRW', DATE '2024-02-01', NULL, 10, '냉장 보관 납품');
INSERT INTO RawContract (RawContractID, VendorID, RawID, ContractPrice, Currency, EffectiveStart, EffectiveEnd, MinOrderQty, Notes) VALUES (3, 2, 30, 8150.75, 'KRW', DATE '2024-03-01', NULL, 8.5, '주2회 배송');
INSERT INTO RawContract (RawContractID, VendorID, RawID, ContractPrice, Currency, EffectiveStart, EffectiveEnd, MinOrderQty, Notes) VALUES (4, 3, 37, 6720.00, 'KRW', DATE '2024-01-15', DATE '2024-12-31', 5, '손질 포함');
INSERT INTO RawContract (RawContractID, VendorID, RawID, ContractPrice, Currency, EffectiveStart, EffectiveEnd, MinOrderQty, Notes) VALUES (5, 3, 36, 9250.25, 'KRW', DATE '2024-04-01', NULL, 6, '냉동 상태');

INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (1, 35, NULL, 'diet01', DATE '2024-07-08', 38.6, 4822.93, DATE '2024-07-13', 'REQUESTED', NULL, NULL, NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (2, 18, NULL, 'diet01', DATE '2024-05-22', 24.6, 1203.17, DATE '2024-05-29', 'APPROVED', 'admin', DATE '2024-05-29', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (3, 47, NULL, 'diet01', DATE '2024-04-20', 12.4, 4271.73, DATE '2024-04-26', 'REQUESTED', NULL, NULL, NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (4, 59, NULL, 'diet01', DATE '2024-03-03', 22.7, 4950.74, DATE '2024-03-10', 'APPROVED', 'admin', DATE '2024-03-10', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (5, 9, NULL, 'diet01', DATE '2024-05-13', 44.0, 2272.1, DATE '2024-05-17', 'REQUESTED', NULL, NULL, NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (6, 30, 3, 'diet01', DATE '2024-06-09', 19.7, 6328.61, DATE '2024-06-14', 'APPROVED', 'admin', DATE '2024-06-14', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (7, 54, NULL, 'diet01', DATE '2024-07-02', 8.7, 1135.68, DATE '2024-07-06', 'REQUESTED', NULL, NULL, NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (8, 42, NULL, 'diet01', DATE '2024-03-25', 8.1, 7701.0, DATE '2024-03-27', 'REQUESTED', NULL, NULL, NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (9, 13, NULL, 'diet01', DATE '2024-04-05', 42.8, 5349.35, DATE '2024-04-10', 'RECEIVED', 'admin', DATE '2024-04-10', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (10, 8, 2, 'diet01', DATE '2024-08-09', 30.4, 2525.75, DATE '2024-08-13', 'REQUESTED', NULL, NULL, NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (11, 39, NULL, 'diet01', DATE '2024-03-25', 32.3, 6235.48, DATE '2024-03-28', 'APPROVED', 'admin', DATE '2024-03-28', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (12, 7, NULL, 'diet01', DATE '2024-07-22', 31.0, 7502.21, DATE '2024-07-27', 'APPROVED', 'admin', DATE '2024-07-27', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (13, 61, NULL, 'diet01', DATE '2024-08-21', 37.2, 1531.98, DATE '2024-08-24', 'REQUESTED', NULL, NULL, NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (14, 45, NULL, 'diet01', DATE '2024-07-04', 39.8, 6952.05, DATE '2024-07-10', 'REQUESTED', NULL, NULL, NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (15, 23, NULL, 'diet01', DATE '2024-03-17', 29.0, 5630.65, DATE '2024-03-24', 'APPROVED', 'admin', DATE '2024-03-24', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (16, 1, 1, 'diet01', DATE '2024-03-14', 43.2, 6756.32, DATE '2024-03-18', 'RECEIVED', 'admin', DATE '2024-03-18', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (17, 58, NULL, 'diet01', DATE '2024-06-06', 42.3, 5951.16, DATE '2024-06-13', 'RECEIVED', 'admin', DATE '2024-06-13', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (18, 62, NULL, 'diet01', DATE '2024-07-25', 34.3, 5311.39, DATE '2024-07-30', 'APPROVED', 'admin', DATE '2024-07-30', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (19, 28, NULL, 'diet01', DATE '2024-05-08', 42.2, 5147.32, DATE '2024-05-10', 'APPROVED', 'admin', DATE '2024-05-10', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (20, 57, NULL, 'diet01', DATE '2024-07-20', 25.3, 6253.33, DATE '2024-07-27', 'APPROVED', 'admin', DATE '2024-07-27', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (21, 22, NULL, 'diet01', DATE '2024-04-16', 6.3, 6956.67, DATE '2024-04-19', 'APPROVED', 'admin', DATE '2024-04-19', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (22, 52, NULL, 'diet01', DATE '2024-07-23', 16.6, 2957.61, DATE '2024-07-27', 'RECEIVED', 'admin', DATE '2024-07-27', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (23, 1, 1, 'diet01', DATE '2024-04-24', 28.2, 2337.39, DATE '2024-04-29', 'APPROVED', 'admin', DATE '2024-04-29', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (24, 36, 5, 'diet01', DATE '2024-08-23', 39.1, 5834.27, DATE '2024-08-28', 'APPROVED', 'admin', DATE '2024-08-28', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (25, 51, NULL, 'diet01', DATE '2024-06-23', 5.8, 3059.65, DATE '2024-06-26', 'APPROVED', 'admin', DATE '2024-06-26', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (26, 43, NULL, 'diet01', DATE '2024-07-12', 31.2, 4312.82, DATE '2024-07-17', 'RECEIVED', 'admin', DATE '2024-07-17', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (27, 36, 5, 'diet01', DATE '2024-05-10', 19.9, 5919.98, DATE '2024-05-14', 'REQUESTED', NULL, NULL, NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (28, 8, 2, 'diet01', DATE '2024-08-18', 37.5, 3208.84, DATE '2024-08-25', 'REQUESTED', NULL, NULL, NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (29, 13, NULL, 'diet01', DATE '2024-08-19', 14.7, 4389.39, DATE '2024-08-25', 'RECEIVED', 'admin', DATE '2024-08-25', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (30, 19, NULL, 'diet01', DATE '2024-05-08', 49.1, 6828.4, DATE '2024-05-12', 'REQUESTED', NULL, NULL, NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (31, 20, NULL, 'diet01', DATE '2024-05-02', 5.6, 4738.95, DATE '2024-05-04', 'RECEIVED', 'admin', DATE '2024-05-04', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (32, 19, NULL, 'diet01', DATE '2024-06-04', 36.4, 1883.96, DATE '2024-06-06', 'RECEIVED', 'admin', DATE '2024-06-06', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (33, 19, NULL, 'diet01', DATE '2024-04-02', 26.1, 4083.28, DATE '2024-04-06', 'APPROVED', 'admin', DATE '2024-04-06', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (34, 8, 2, 'diet01', DATE '2024-03-19', 42.0, 3804.95, DATE '2024-03-26', 'RECEIVED', 'admin', DATE '2024-03-26', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (35, 4, NULL, 'diet01', DATE '2024-05-03', 11.8, 6677.99, DATE '2024-05-06', 'REQUESTED', NULL, NULL, NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (36, 36, 5, 'diet01', DATE '2024-07-08', 39.4, 5244.22, DATE '2024-07-14', 'APPROVED', 'admin', DATE '2024-07-14', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (37, 29, NULL, 'diet01', DATE '2024-07-14', 45.9, 3081.47, DATE '2024-07-18', 'RECEIVED', 'admin', DATE '2024-07-18', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (38, 40, NULL, 'diet01', DATE '2024-03-25', 7.7, 7720.76, DATE '2024-03-28', 'RECEIVED', 'admin', DATE '2024-03-28', NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (39, 14, NULL, 'diet01', DATE '2024-04-06', 16.9, 1568.31, DATE '2024-04-12', 'REQUESTED', NULL, NULL, NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (40, 11, NULL, 'diet01', DATE '2024-07-16', 5.1, 4153.53, DATE '2024-07-20', 'REQUESTED', NULL, NULL, NULL);
INSERT INTO PurchaseRequest (PurchaseRequestID, RawID, RawContractID, RequestedBy, RequestedDate, Quantity, UnitPriceEstimate, ExpectedDeliveryDate, Status, ApprovedBy, ApprovedDate, Remark) VALUES (41, 37, 4, 'diet01', DATE '2024-08-15', 18.5, 7120.5, DATE '2024-08-20', 'REQUESTED', NULL, NULL, '추가 고등어 재고');

COMMIT;
